AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auto-create-3d-demention

Parameters:
  MovieBucketName:
    Type: String
    Default: 'three-dementions-movie'
  # ImageBucketName:
  #   Type: String
  #   Default: 'three-dementions-image'
  # SqsQueueName:
  #   Type: String
  #   Default: 'three-dementions-sqs-image'

Resources:
  S3InputMovieBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MovieBucketName
  # S3InputImageBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Ref ImageBucketName
  #   DependsOn: S3InputMovieBucket
  S3InputFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.callS3
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref Layer
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3InputMovieBucket
            Events: s3:ObjectCreated:*
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: three-demention
      ContentUri: .
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: makefile
