AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auto-create-3d-demention

Parameters:
  MovieBucketName:
    Type: String
    Default: 'three-dementions-movie-dev'
  ImageBucketName:
    Type: String
    Default: 'three-dementions-image-dev'
  # SqsQueueName:
  #   Type: String
  #   Default: 'three-dementions-sqs-image'

Resources:
  MovieBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MovieBucketName
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ImageBucketName
  CallFfmpegFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.callFfmpeg
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref Layer
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref MovieBucket
            Events: s3:ObjectCreated:*
  ConvertMovieToImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.convertMovieToImage
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref Layer
      MemorySize: 128
      Timeout: 300
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref MovieBucket
        - S3WritePolicy:
            BucketName: !Ref ImageBucket
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: three-demention
      ContentUri: .
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: makefile
  SampleSNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SampleSNSTopic
      TopicName: SampleSNSTopic
