AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auto-create-3d-demention

Resources:
  S3SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: '3d-dementions-movie'
  s3InputFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.callS3
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref Layer
      MemorySize: 128
      Timeout: 300
      Policies:
        - S3ReadPolicy:
            BucketName: '3d-dementions-movie'
        - S3WritePolicy:
            BucketName: '3d-dementions-movie'
      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: '3d-dementions-movie'
            Events: s3:ObjectCreated:*
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: 3d-demention
      ContentUri: .
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: makefile
